### ISSUE TITLE
Erm the name DINOTICK makes no sense 

### ISSUE THREAD

**Issue by 1629JE** [DINOTICK-Dev/DINOTICK-Dev#1]
As the world renown developer Benedict D. Over, you are honestly the worst developer I have ever seen! Honestly, Who has an AirPod as their profile! This “DINOTICK-DEV”should be changed to “AIRPODTICK-GAY” as it better suits you. Also, kill yourself, for literally no reason. Now if you don’t mind me, I’m going to make a mod for a “Minecraft, but _____” video. I need to go talk to someone about this “Rav” fellow, his music is just preposterous! SMH.

**Comment by DINOTICK-Dev** [comment]
j
